/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Livro.UI;

import controller.UI.LivroControllerUI;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import util.PrintUtil;

/**
 *Classe responsável pela interface do cadastro de um Livro e de um Livro;
 * @author Diego Peixoto
 * @author Tainara Specht
 */
public class PainelCadastroLivro extends javax.swing.JPanel {

    private LivroControllerUI controller;
    private JanelaCrudLivro janela;

    /**
     * Creates new form PainelCadastroLivro
     */
    public PainelCadastroLivro(LivroControllerUI controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        labelPainelFormulario = new javax.swing.JLabel();
        botaoSalvar = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        textISBN = new javax.swing.JTextField();
        textTitulo = new javax.swing.JTextField();
        textEditora = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textAutor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textAnoPublicacao = new javax.swing.JTextField();

        jLabel4.setText("Editora:");

        labelPainelFormulario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPainelFormulario.setText("Cadastro de Livros");

        botaoSalvar.setText("Cadastrar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jLabel1.setText("ISBN:");

        jLabel2.setText("Titulo:");

        jLabel5.setText("Autor(es):");

        jLabel6.setText("Ano de Publicação:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPainelFormulario)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoSalvar)
                        .addGap(102, 102, 102)
                        .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(21, 21, 21)
                            .addComponent(textAnoPublicacao))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textISBN)
                                .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(21, 21, 21)
                            .addComponent(textEditora, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelPainelFormulario)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAnoPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoVoltar))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        if (this.textISBN.getText().equals("") || this.textTitulo.getText().equals("") || this.textEditora.getText().equals("") || this.textAutor.getText().equals("")
                || this.textAnoPublicacao.getText().equals("")) {
            PrintUtil.printMessageSucesso(janela, "Todos os campos devem ser preenchidos!");
        } else {
            controller.salvarLivro(
                    this.textISBN.getText(),
                    this.textTitulo.getText(),
                    this.textEditora.getText(),
                    this.textAutor.getText(),
                    this.textAnoPublicacao.getText());
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        controller.voltarPrincipal();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    public JButton getBotaoSalvar() {
        return botaoSalvar;
    }

    public JButton getBotaoVoltar() {
        return botaoVoltar;
    }

    public JTextField getTextAnoPublicacao() {
        return textAnoPublicacao;
    }

    public JTextField getTextAutor() {
        return textAutor;
    }

    public JTextField getTextEditora() {
        return textEditora;
    }

    public JTextField getTextISBN() {
        return textISBN;
    }

    public JTextField getTextTitulo() {
        return textTitulo;
    }

    public JLabel getLabelPainelFormulario() {
        return labelPainelFormulario;
    }

    /**
     * Método responsável por zerar os campos de RG, nome e telefone no cadastro de um livro;
     */
    public void zerarCampos() {
        this.textISBN.setText("");
        this.textTitulo.setText("");
        this.textEditora.setText("");
        this.textAutor.setText("");
        this.textAnoPublicacao.setText("");
    }

    /**
     * Método que carrega os dados de um Livro;
     * @param isbn - recebe o isbn de um livro;
     * @param titulo - recebe o título de um livro;
     * @param editora - recebe a editora de um livro;
     * @param autor - recebe o(s) autor(es) de um livro;
     * @param anoPublicacao - recebe o ano de publicação de um livro;
     */
    public void carregaDados(String isbn, String titulo, String editora, String autor, String anoPublicacao) {
        this.textISBN.setText(isbn);
        this.textTitulo.setText(titulo);
        this.textEditora.setText(editora);
        this.textAutor.setText(autor);
        this.textAnoPublicacao.setText(anoPublicacao);
    }

    /**
     * Método para permitir a edição de um formulário na janela;
     * @param valor - recebe 'true' ou 'false';
     */
    public void habilitaEdicaoFormLivro(boolean valor) {
        this.textISBN.setEditable(valor);
        this.textTitulo.setEditable(valor);
        this.textEditora.setEditable(valor);
        this.textAutor.setEditable(valor);
        this.textAnoPublicacao.setEditable(valor);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel labelPainelFormulario;
    private javax.swing.JTextField textAnoPublicacao;
    private javax.swing.JTextField textAutor;
    private javax.swing.JTextField textEditora;
    private javax.swing.JTextField textISBN;
    private javax.swing.JTextField textTitulo;
    // End of variables declaration//GEN-END:variables
}
